name: build

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)  
    steps:
      - uses: actions/checkout@v6
      - uses: dart-lang/setup-dart@v1
      - run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: latest
      - run: dart pub get

      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze --fatal-warnings
      - run: dart test
        working-directory: sync_config_tools

      - run: pnpm build
        working-directory: js-package
      - run: pnpm test
        working-directory: js-package
